---
Name: opengraphmeta
After:
  - 'siteconfig/*'
Before:
  - 'mysite'
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    - ToastNZ\OpenGraphMeta\Extensions\OpenGraphMeta

SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - ToastNZ\OpenGraphMeta\Extensions\OpenGraphSiteConfigExtension
